# Refactor Toolkit Configuration (Optional)
#
# This file allows you to customize validation behavior for your project.
# All settings are optional - the toolkit works fine without this file.
#
# To use: Copy this file to your project root as `.refactor-toolkit.yaml`
# or place it in the directory you're validating.

# Whitelist patterns to eliminate false positives
whitelists:
  # Dead code detection - files/patterns to ignore
  # Use this for configuration files, constants, or public APIs
  dead_code_ignore:
    # Example: Ignore all config files
    # - "**/*_config.py"
    # - "**/constants.py"
    # - "**/settings.py"

  # Security scan - error codes to ignore
  # Use this for intentional patterns (e.g., try-except-pass)
  security_ignore:
    # Example: Ignore intentional try-except patterns
    # - "B110"  # try-except-pass
    # - "B112"  # try-except-continue

  # Import checks - files to skip
  import_ignore:
    # Example: Skip test files
    # - "**/test_*.py"
    # - "**/conftest.py"

# Path configurations (relative to target directory)
paths:
  # Where to look for tests
  test_directories:
    - tests
    - ../tests # For when validating src/ directory
    - test

  # Where to look for documentation
  doc_files:
    - README.md
    - ../README.md # For when validating src/ directory
    - docs/README.md
